# Generated by Django 3.2.8 on 2021-11-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('lastname', models.CharField(max_length=30, verbose_name='Lastname')),
                ('IDKind', models.CharField(max_length=30, verbose_name='IDKind')),
                ('IDNumber', models.CharField(max_length=30, verbose_name='IDNumber')),
                ('address', models.CharField(max_length=30, verbose_name='address')),
                ('city', models.CharField(max_length=30, verbose_name='city')),
                ('country', models.CharField(max_length=30, verbose_name='country')),
                ('landline', models.CharField(max_length=30, verbose_name='landline')),
                ('mobilephone', models.CharField(max_length=30, verbose_name='mobilephone')),
                ('jobs', models.CharField(default='No Aplica', max_length=30, verbose_name='jobs')),
                ('company', models.CharField(default='No Aplica', max_length=30, verbose_name='company')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('rol', models.CharField(choices=[('AD', 'Administrador'), ('OT', 'Otorgante'), ('AP', 'Adoptante')], default='AP', max_length=2)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
